### ISSUE TITLE
sourceless file: simplebar.js

### ISSUE THREAD

**Issue by kilobyte** [crawl/crawl#835]
**0.22.0** includes a file ``source/webserver/game_data/static/simplebar.js`` that's the result of compiling a bunch of npm modules into a non-human-readable/editable form.

Besides being unacceptable for Debian, this is also a GPL violation: if a body of work (not merely bundled) contains non-GPL pieces, they must not only be of GPL-compatible licenses (MIT here, that's ok), but also come in preferred form for modification (which preprocessed and minified javascript certainly is not).

All other Javascript files are in proper source form; they can get combined/minified later but only as a part of the build process.

For now, as Debian doesn't ship webtiles builds, I simply repacked the tarball to exclude this file.

**Comment by rawlins** [comment]
> that's the result of compiling a bunch of npm modules into a non-human-readable/editable form.

Can you clarify where exactly this characterization comes from? In point of fact, this file (plus the .css) is from release v. 2.5.1 of the simplebar library from https://github.com/Grsmto/simplebar. This together with the licensing information for that library is described in a human-readable comment at the top of `simplebar.js`; the file is nearly diff identical (with only 4 whitespace changes that are probably accidental, though I'm not sure where they came from) with the distributed minified version from the relevantly versioned package at that site. It probably ought to be in a `contrib` folder to clarify the situation, but as far as I'm aware the situation is exactly the same as anything to be found in of `/crawl-ref/source/webserver/static/scripts/contrib`.

> Besides being unacceptable for Debian

Can you clarify (preferably with a link) what specific Debian policies are being violated, if this is anything over and above the GPL issue?

**Comment by kilobyte** [comment]
You cannot merely say that source for simplebar is somewhere on the Internet, requiring a few pieces located elsewhere, plus a slew of npm modules required to compile simplebar into the combined+minified version.  If a compiled form is shipped, GPL requires shipping source as well.

> as far as I'm aware the situation is exactly the same as anything to be found in /crawl-ref/source/webserver/static/scripts/contrib.

No — those pieces are not shipped as a part of the package (at least not -nodeps), simplebar is.

Any "real" libraries shipped in the contrib tarball include full source.  I see that a few of other pieces of Javascript also have this problem, but 1. I don't care about the contrib tarball right now (but it also should be fixed eventually), and 2. two wrongs don't make a right.

> Can you clarify (preferably with a link) what specific Debian policies are being violated, if this is anything over and above the GPL issue?

DFSG §2, GPL2 §1 — these are pretty much the same.

I don't see how preprocessed+combined+minified Javascript could be considered "preferred form for modification".  This question has been pretty settled in Debian: despite being pure ASCII, such javascipt files are not different from assembled+linked C code turned into an x86 executable.  You *can* disassemble an x86 binary to turn into a text form that in principle can be modified, but GPL2 §1 requires actual source.  Plus build scripts (like a Makefile).

**Comment by rawlins** [comment]
Ok, thanks for the detailed followup, that was helpful (to me at least) in clarifying what exactly are the issues raised here.

For now I have removed `simplebar.js` from the nodeps tarbell build, and that tarbell on the official site is (or should soon be) updated.

**Comment by rawlins** [comment]
This should be fully resolved for `simplebar.js` as of 1502417413e94; the version in the repository is combined (from several MIT-licensed packages) but is not minified or otherwise obfuscated, and is human-readable/editable. It is still not included in nodeps.
